env:
  browser: true
  es2021: true
extends:
  - "react-app"
  - "react-app/jest"
plugins:
  - prettier
rules:
  "prettier/prettier":
    - warn
    - "bracketSameLine": true
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
